### PR TITLE
Minor misspell fixes

### PR DESCRIPTION
**Pull request by hiveminded**
Files changed:

1. [node_modules/jstimezonedetect/dist/jstz.js](https://github.com/ossfriday/ossfriday/blob/master/node_modules/jstimezonedetect/dist/jstz.js)
2. [node_modules/primer-alerts/CHANGELOG.md](https://github.com/ossfriday/ossfriday/blob/master/node_modules/primer-alerts/CHANGELOG.md)
3. [node_modules/primer-markdown/lib/lists.scss](https://github.com/ossfriday/ossfriday/blob/master/node_modules/primer-markdown/lib/lists.scss)
4. [node_modules/primer-navigation/README.md](https://github.com/ossfriday/ossfriday/blob/master/node_modules/primer-navigation/README.md)
5. [node_modules/primer-truncate/README.md](https://github.com/ossfriday/ossfriday/blob/master/node_modules/primer-truncate/README.md)

Relative PRs to the external repositories:

Checked: **upstream merged**
Unchecked: **upstream, not yet merged**
- [ ] https://github.com/pellepim/jstimezonedetect/pull/2
- [ ] https://github.com/primer/primer-alerts/pull/1
- [ ] https://github.com/primer/primer-markdown/pull/70
- [ ] https://github.com/primer/primer-navigation/pull/2
- [ ] https://github.com/primer/primer-truncate/pull/1

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
Awesome, thanks! Can you make the issue body a list of checkboxes and check them off as they are merged upstream?

**Comment by hiveminded** [comment]
@MikeMcQuaid You're welcome! Could you review the body again, please?  You have the permission to change the body if it's not ok yet.

**Comment by MikeMcQuaid** [comment]
@hiveminded That's great, thanks! Give me a shout when they are all merged 👍

**Comment by hiveminded** [comment]
@MikeMcQuaid  I can agree but I think that you don't have to depend on an external author to apply these fixes. I have fixed the misspells to this repository too for this purpose, third-party authors may login to github after 2 years, we will wait so long?

**Comment by MikeMcQuaid** [comment]
@hiveminded Given none of these changes are user visible I think it's worth waiting for upstream. Otherwise if we update these `npm` modules the problems will return again. Sorry!

**Comment by hiveminded** [comment]
@MikeMcQuaid No need to sorry I had that answer in mind too, I understand. Let's wait then :)

**Comment by MikeMcQuaid** [comment]
@hiveminded Thanks for the issue and PRs but closing this for now.

**Comment by hiveminded** [comment]
Alright, no worries!

**Pull request closed without merging**
