### PR TITLE
Changed "their" to "your" for logged in users

### LINKED ISSUE #120: Typo: "their" -> "your" for logged in state
From my profile while logged in:

screen shot 2017-06-29 at 8 43 52 am

If user is current, this should say `in your last 1,000 events`. If logged out, `their`.

Or just edit to neutral copy, like `in the last 1,000 events` :wink:

### PR DESCRIPTION
**Pull request by DavidAylaian**
See issue #120 for details.

Fixes #120

### CODE REVIEW

**Comment by MikeMcQuaid** [comment]
@DavidAylaian Tests are failing as the syntax used isn't correct. Can you take a look: https://travis-ci.org/ossfriday/ossfriday/builds/248696799?utm_source=github_status&utm_medium=notification

Thanks!

**Comment by DavidAylaian** [comment]
@MikeMcQuaid I looked, but it's failing on lines that I didn't change? Sorry if I'm missing something here.

**Comment by MikeMcQuaid** [comment]
@DavidAylaian `master` is not failing so it is this PR I'm afraid. I'd suggest instead something like:
```erb
<%= @user_is_current ? "your" : "their" %>
```

**Comment by DavidAylaian** [comment]
@MikeMcQuaid thanks, I'll give it a try.

**Comment by MikeMcQuaid** [comment]
Sorry, I misread, the issue is trying to do `erb` inside another `erb`. Try:

```ruby
#{@user_is_current ? "your" : "their"}
```

**Comment by DavidAylaian** [comment]
@MikeMcQuaid looks right to me.

**Comment by DavidAylaian** [comment]
@MikeMcQuaid it passed. Thanks for helping debug my code!

**Comment by MikeMcQuaid** [comment]
Thanks for your contribution to Open Source Friday (on a Friday, no less)! You rock!

**Pull request merged**
